[{"ContainerToolsException.Message":"Failed to stop the application within the container. Build may fail because the files are in use. Docker command failed with exit code 126.","ContainerToolsException.ErrorCode":"CTP1006","ContainerToolsException.StackTrace":"   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__26.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 126.\r\n   at Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<ExecAsync>d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\nError code: CTC1029\r\nSeverity: Error\r\nCommand line: docker exec -i b7d4bfb841503b94992841f5ce031174f57b81f35df5a308382fc1f9587b7664 /bin/sh -c \"if PID=$(pidof dotnet); then kill $PID; fi\"\r\nCommand exit code: 126\r\nCommand output: OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused \"chdir to cwd (\\\"/app\\\") set in config.json failed: input/output error\": unknown\r\nCommand error: \r\n"},{"ContainerToolsException.Message":"Failed to stop the application within the container. Build may fail because the files are in use. Docker command failed with exit code 126.","ContainerToolsException.ErrorCode":"CTP1006","ContainerToolsException.StackTrace":"   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__26.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Docker command failed with exit code 126.\r\n   at Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<ExecAsync>d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\nError code: CTC1029\r\nSeverity: Error\r\nCommand line: docker exec -i b7d4bfb841503b94992841f5ce031174f57b81f35df5a308382fc1f9587b7664 /bin/sh -c \"if PID=$(pidof dotnet); then kill $PID; fi\"\r\nCommand exit code: 126\r\nCommand output: OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused \"chdir to cwd (\\\"/app\\\") set in config.json failed: input/output error\": unknown\r\nCommand error: \r\n"}]